---  
  - yum: pkg={{ item }} state=present
    with_items:
      - net-tools
      
  - file: path={{ item }} owner=rtws group=rtws mode=0755 state=directory recurse=yes
    with_items:
      - /usr/local/rtws/h2logs
          
  - copy: src=bootstrap dest=/sbin/bootstrap owner=rtws group=rtws mode=0544 force=yes
     
  - name: Add RTWS_IS_GATEWAY to rtwsrc
    lineinfile: dest=/etc/rtwsrc line="RTWS_IS_GATEWAY=true" insertafter=EOF
      
  - file: path={{ rtws_home }} owner=rtws group=rtws mode=0755 state=directory recurse=yes
  
  - file: path=/mnt/rdafs owner=rtws group=rtws mode=0755 state=directory
      
  - include: cleanup.yml