---  
  - yum: pkg={{ item }} state=absent
    with_items:
      - wget
      
  - shell: yum -y clean all
  
  - file: path={{ item }} state=absent
    with_items:
      - "/var/lib/yum/history"
      - "/var/log/anaconda"
  
  - file: path=/var/log/yum.log state=absent