---
  # Split out creating users and their home directories due to bug when running a centos host and a ubuntu
  # docker container.  Reference: http://www.fewbytes.com/docker-selinux-and-the-myth-of-kernel-indipendence/
  - name: Adding the rtws group
    group: name=rtws gid=1001 state=present
      
  - name: Adding the rtws user
    user: name=rtws uid=1001 shell=/bin/bash createhome=no state=present group=rtws groups=
  
  - name: Adding the activemq group
    group: name=activemq gid=1004 state=present
    
  - name: Adding the activemq user
    user: name=activemq uid=1004 shell=/bin/bash createhome=no state=present group=activemq groups=
 
  - file: path=/home/rtws owner=rtws group=rtws mode=0775 state=directory
  
  - file: path=/home/activemq owner=activemq group=activemq mode=0755 state=directory