# Dockerfile for building a kibana image for use by a system in appliance mode
# Remember, each action in the current version of Docker creates a new revision to the image
# being built so minimize the number of actions required to reduce the revisions necessary
# to create the appliance image.

FROM centos:7.2.1511

RUN yum install -y wget sudo tar logrotate && groupadd -g 1001 rtws && adduser -g 1001 -m -r -u 1001 rtws

COPY no_border.png /tmp/no_border.png

RUN wget -q --no-check-certificate -O /tmp/kibana-4.0.1-linux-x64.tar.gz https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz && \
	tar -C /usr/local -xzf /tmp/kibana-4.0.1-linux-x64.tar.gz && \
	mv -fv /tmp/no_border.png /usr/local/kibana-4.0.1-linux-x64/src/public/images/no_border.png && \
	chown -R rtws:rtws /usr/local/kibana-4.0.1-linux-x64 && \
	rm -f /tmp/kibana-4.0.1-linux-x64.tar.gz && \
	yum -y clean all

EXPOSE 5601

# Set usr/bin/mongod as the dockerized entry-point application
ENTRYPOINT sed -i "s/localhost/elasticsearch1.$RTWS_DOMAIN/g" /usr/local/kibana-4.0.1-linux-x64/config/kibana.yml && su - rtws /usr/local/kibana-4.0.1-linux-x64/bin/kibana