# Dockerfile for building a mongodb image for use by a system in appliance mode
# Remember, each action in the current version of Docker creates a new revision to the image
# being built so minimize the number of actions required to reduce the revisions necessary
# to create the appliance image.

FROM ubuntu:12.04

# Import MongoDB public GPG key AND create a MongoDB list file
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list

# Update apt-get sources AND install MongoDB
RUN apt-get -y update && apt-get install -y --force-yes mongodb-org=3.0.3 && apt-get install -y --force-yes mongodb-org=3.0.3 mongodb-org-server=3.0.3 mongodb-org-shell=3.0.3 mongodb-org-mongos=3.0.3 mongodb-org-tools=3.0.3 && apt-get -y clean all

# Create the MongoDB data directory
RUN mkdir -p /mnt/rdafs

# Expose port 27017 from the container to the host
EXPOSE 27017

# Set usr/bin/mongod as the dockerized entry-point application
ENTRYPOINT usr/bin/mongod --dbpath /mnt/rdafs