---
  - name: Downloading ActiveMQ 5.12.0
    get_url: url=http://archive.apache.org/dist/activemq/5.12.0/apache-activemq-5.12.0-bin.tar.gz dest=/usr/local/apache-activemq-5.12.0-bin.tar.gz
        
  - name: Unpack ActiveMQ
    command: tar -xzvf /usr/local/apache-activemq-5.12.0-bin.tar.gz
    args:
      chdir: /usr/local/
      creates: /usr/local/apache-activemq-5.12.0
      
  - command: ln -sf /usr/local/apache-activemq-5.12.0 /usr/local/apache-activemq
  
  - command: mv /usr/local/apache-activemq-5.12.0/conf/activemq.xml /usr/local/apache-activemq-5.12.0/conf/activemq-default.xml
    args:
      creates: /usr/local/apache-activemq-5.12.0/conf/activemq-default.xml
    
  - name: Set ownership on ActiveMQ
    command: chown -R activemq:activemq /usr/local/apache-activemq-5.12.0
      
  - name: Cleanup
    command: rm -f /usr/local/apache-activemq-5.12.0-bin.tar.gz
    args:
      removes: /usr/local/apache-activemq-5.12.0-bin.tar.gz